In [1]:
import numpy as np
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                [65.4, 59.2, 63.6, 88.4, 68.7]])
print(np_2d)

[[ 1.73  1.68  1.71  1.89  1.79]
 [65.4  59.2  63.6  88.4  68.7 ]]


In [2]:
np_2d.shape

(2, 5)

In [3]:
np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
        [65.4, 59.2, 63.6, 88.4, '68.7']])

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], dtype='<U32')

In [4]:
numeros = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15]])
print(numeros.shape)

(3, 5)


In [5]:
numeros2 = np.array ([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
print(numeros2.shape)

(3, 3)


In [6]:
print(np_2d[0, 2])
print(np_2d[:, 1:3])
print(np_2d[1, :])

1.71
[[ 1.68  1.71]
 [59.2  63.6 ]]
[65.4 59.2 63.6 88.4 68.7]


In [7]:
#create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]
import numpy as np
np_baseball = np.array(baseball)
print(type(np_baseball))
print(np_baseball.shape)

<class 'numpy.ndarray'>
(8,)


In [8]:
import random as rd
import numpy as np
# geração de números entre 150 e 209
height = range(150 , 210)
print(height)
#geração de números entre 50 e 149
weight = range(50, 150)
print(weight)
#amostra randomica de 20 números de height
height = rd.sample(height,20)
print(height)
#amostra randomica de 20 numeros de weight
weight = rd.sample(weight,20)
print(weight)
#converter height em array e normalizar multiplicador por 0.01
height_array = np.array(height) * 0.01
print(height_array)
#converter weight em array
weight_array = np.array(weight)
print(weight_array)
#calculo do bmi
bmi = weight_array/ height_array ** 2
print(bmi)
#verificação onde bmi é menor que 21
light = bmi<21
print(light)
print(bmi[bmi < 21])
print(weight_array[8:16])
print(height_array[11:20])



range(150, 210)
range(50, 150)
[204, 171, 192, 164, 206, 160, 166, 172, 209, 178, 168, 184, 161, 174, 180, 190, 183, 182, 162, 177]
[142, 68, 141, 145, 86, 136, 91, 74, 140, 75, 105, 147, 83, 131, 53, 82, 72, 87, 66, 126]
[2.04 1.71 1.92 1.64 2.06 1.6  1.66 1.72 2.09 1.78 1.68 1.84 1.61 1.74
 1.8  1.9  1.83 1.82 1.62 1.77]
[142  68 141 145  86 136  91  74 140  75 105 147  83 131  53  82  72  87
  66 126]
[34.12149173 23.25501864 38.24869792 53.91136228 20.26581205 53.125
 33.02366091 25.01352082 32.05054829 23.67125363 37.20238095 43.41918715
 32.02036958 43.26859559 16.35802469 22.71468144 21.49959688 26.26494385
 25.1486054  40.21832807]
[False False False False  True False False False False False False False
 False False  True False False False False False]
[20.26581205 16.35802469]
[140  75 105 147  83 131  53  82]
[1.84 1.61 1.74 1.8  1.9  1.83 1.82 1.62 1.77]


In [9]:
#
baseball = [[180, 78.4],
            [215, 102],
            [210, 98.5],
            [188, 75.2]]
#
import numpy as np
#
np_baseball = np.array(baseball)
#
print(np_baseball[2])
np_weight_lb = np_baseball[:, 1]
print(np_weight_lb)
print(np_baseball[1, 0])
#
media = np.mean(np_baseball[:, 0])
print(media)
mediana = np.median(np_baseball[1, :])
print(mediana)

[210.   98.5]
[ 78.4 102.   98.5  75.2]
215.0
198.25
158.5
