In [10]:
import numpy as np
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                [65.4, 59.2, 63.6, 88.4, 68.7]])
print(np_2d)

[[ 1.73  1.68  1.71  1.89  1.79]
 [65.4  59.2  63.6  88.4  68.7 ]]


In [11]:
np_2d.shape

(2, 5)

In [13]:
np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
        [65.4, 59.2, 63.6, 88.4, '68.7']])

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], dtype='<U32')

In [17]:
numeros = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15]])
print(numeros.shape)

(3, 5)


In [20]:
numeros2 = np.array ([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
print(numeros2.shape)

(3, 3)


In [26]:
print(np_2d[0, 2])
print(np_2d[:, 1:3])
print(np_2d[1, :])

1.71
[[ 1.68  1.71]
 [59.2  63.6 ]]
[65.4 59.2 63.6 88.4 68.7]


In [45]:
#create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]
import numpy as np
np_baseball = np.array(baseball)
print(type(np_baseball))
print(np_baseball.shape)

<class 'numpy.ndarray'>
(8,)


In [56]:
import random as rd
import numpy as np
# geração de números entre 150 e 209
height = range(150 , 210)
print(height)
#geração de números entre 50 e 149
weight = range(50, 150)
print(weight)
#amostra randomica de 20 números de height
height = rd.sample(height,20)
print(height)
#amostra randomica de 20 numeros de weight
weight = rd.sample(weight,20)
print(weight)
#converter height em array e normalizar multiplicador por 0.01
height_array = np.array(height) * 0.01
print(height_array)
#converter weight em array
weight_array = np.array(weight)
print(weight_array)
#calculo do bmi
bmi = weight_array/ height_array ** 2
print(bmi)
#verificação onde bmi é menor que 21
light = bmi<21
print(light)
print(bmi[bmi < 21])
print(weight_array[8:16])
print(height_array[11:20])



range(150, 210)
range(50, 150)
[169, 181, 164, 153, 193, 197, 162, 158, 177, 165, 186, 160, 150, 190, 202, 184, 188, 208, 168, 163]
[60, 94, 87, 58, 135, 65, 108, 149, 128, 61, 127, 84, 93, 54, 109, 134, 81, 126, 138, 130]
[1.69 1.81 1.64 1.53 1.93 1.97 1.62 1.58 1.77 1.65 1.86 1.6  1.5  1.9
 2.02 1.84 1.88 2.08 1.68 1.63]
[ 60  94  87  58 135  65 108 149 128  61 127  84  93  54 109 134  81 126
 138 130]
[21.0076678  28.69265285 32.34681737 24.77679525 36.24258369 16.74869231
 41.15226337 59.68594776 40.85671423 22.40587695 36.70944618 32.8125
 41.33333333 14.95844875 26.71306735 39.57939509 22.91760978 29.12352071
 48.89455782 48.92920321]
[False False False False False  True False False False False False False
 False  True False False False False False False]
[16.74869231 14.95844875]
[128  61 127  84  93  54 109 134]
[1.6  1.5  1.9  2.02 1.84 1.88 2.08 1.68 1.63]


In [65]:
#
baseball = [[180, 78.4],
            [215, 102],
            [210, 98.5],
            [188, 75.2]]
#
import numpy as np
#
np_baseball = np.array(baseball)
#
print(np_baseball[2])
np_weight_lb = np_baseball[:, 1]
print(np_weight_lb)
print(np_baseball[1, 0])
#
media = np.mean(np_baseball[:, 0])
print(media)
mediana = np.median(np_baseball[1, :])
print(mediana)

[210.   98.5]
[ 78.4 102.   98.5  75.2]
215.0
198.25
158.5
