In [1]:
import numpy as np
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                [65.4, 59.2, 63.6, 88.4, 68.7]])
print(np_2d)

[[ 1.73  1.68  1.71  1.89  1.79]
 [65.4  59.2  63.6  88.4  68.7 ]]


In [2]:
np_2d.shape

(2, 5)

In [3]:
np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
        [65.4, 59.2, 63.6, 88.4, '68.7']])

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], dtype='<U32')

In [4]:
numeros = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15]])
print(numeros.shape)

(3, 5)


In [5]:
numeros2 = np.array ([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
print(numeros2.shape)

(3, 3)


In [6]:
print(np_2d[0, 2])
print(np_2d[:, 1:3])
print(np_2d[1, :])

1.71
[[ 1.68  1.71]
 [59.2  63.6 ]]
[65.4 59.2 63.6 88.4 68.7]


In [7]:
#create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]
import numpy as np
np_baseball = np.array(baseball)
print(type(np_baseball))
print(np_baseball.shape)

<class 'numpy.ndarray'>
(8,)


In [8]:
import random as rd
import numpy as np
# geração de números entre 150 e 209
height = range(150 , 210)
print(height)
#geração de números entre 50 e 149
weight = range(50, 150)
print(weight)
#amostra randomica de 20 números de height
height = rd.sample(height,20)
print(height)
#amostra randomica de 20 numeros de weight
weight = rd.sample(weight,20)
print(weight)
#converter height em array e normalizar multiplicador por 0.01
height_array = np.array(height) * 0.01
print(height_array)
#converter weight em array
weight_array = np.array(weight)
print(weight_array)
#calculo do bmi
bmi = weight_array/ height_array ** 2
print(bmi)
#verificação onde bmi é menor que 21
light = bmi<21
print(light)
print(bmi[bmi < 21])
print(weight_array[8:16])
print(height_array[11:20])



range(150, 210)
range(50, 150)
[189, 173, 206, 185, 158, 164, 205, 163, 197, 202, 175, 150, 182, 200, 170, 207, 193, 157, 192, 166]
[65, 79, 78, 116, 131, 53, 138, 50, 68, 62, 113, 110, 61, 52, 142, 146, 124, 125, 73, 85]
[1.89 1.73 2.06 1.85 1.58 1.64 2.05 1.63 1.97 2.02 1.75 1.5  1.82 2.
 1.7  2.07 1.93 1.57 1.92 1.66]
[ 65  79  78 116 131  53 138  50  68  62 113 110  61  52 142 146 124 125
  73  85]
[18.19657904 26.3958034  18.38062023 33.89335281 52.47556481 19.70553242
 32.83759667 18.81892431 17.52170888 15.19458877 36.89795918 48.88888889
 18.41565028 13.         49.1349481  34.07314056 33.28948428 50.71199643
 19.80251736 30.84627667]
[ True False  True False False  True False  True  True  True False False
  True  True False False False False  True False]
[18.19657904 18.38062023 19.70553242 18.81892431 17.52170888 15.19458877
 18.41565028 13.         19.80251736]
[ 68  62 113 110  61  52 142 146]
[1.5  1.82 2.   1.7  2.07 1.93 1.57 1.92 1.66]


In [9]:
#
baseball = [[180, 78.4],
            [215, 102],
            [210, 98.5],
            [188, 75.2]]
#
import numpy as np
#
np_baseball = np.array(baseball)
#
print(np_baseball[2])
np_weight_lb = np_baseball[:, 1]
print(np_weight_lb)
print(np_baseball[1, 0])
#
media = np.mean(np_baseball[:, 0])
print(media)
mediana = np.median(np_baseball[1, :])
print(mediana)

[210.   98.5]
[ 78.4 102.   98.5  75.2]
215.0
198.25
158.5
