In [3]:
import numpy
# array([1, 2, 3]) tem que colocar o a biblioteca numpy. antes

In [4]:
numpy.array([1, 2, 3])

array([1, 2, 3])

In [5]:
import numpy as np # com esse comando irei poder abreviar o numpy para np
np.array([1, 2, 3])

array([1, 2, 3])

In [6]:
from numpy import array # comando para n ter que colocar o numpy antes
array([1, 2, 3])

array([1, 2, 3])

In [7]:
import numpy as np
fam = ['Liz', 1.73, 'Emma', 1.68, 'Mom', 1.71, 'Dad', 1.89]
fam_ext = fam + ['Me', 1.79]
print(fam_ext)
print(type(fam_ext))
print(str(len(fam_ext)) + 'elements in fam_ext')
np_fam = np.array(fam_ext)

['Liz', 1.73, 'Emma', 1.68, 'Mom', 1.71, 'Dad', 1.89, 'Me', 1.79]
<class 'list'>
10elements in fam_ext


In [8]:
# difinition of radius
r = 0.43
# import the math package
import math
# calculate c
c =  2 * math.pi * r
# calculate a
a = math.pi * r ** 2
# build printout
print('Circuference: ' + str(c))
print('área: ' + str(a))

Circuference: 2.701769682087222
área: 0.5808804816487527


In [9]:
height = [1.70, 1.80, 1.72, 1.65, 1.83]
print(height)
weight = [82, 70, 75, 63, 76]
print(weight)
# weight/ height ** 2 (não tem como fazer uma divisão de listas sem o numpy)

[1.7, 1.8, 1.72, 1.65, 1.83]
[82, 70, 75, 63, 76]


In [10]:
np_height = np.array(height)
print(np_height)
np_weight = np.array(weight)
print(np_weight)
bmi = np_weight / np_height ** 2
print(bmi)

[1.7  1.8  1.72 1.65 1.83]
[82 70 75 63 76]
[28.37370242 21.60493827 25.35154137 23.14049587 22.69401893]


In [11]:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])
print(python_list + python_list)
print(numpy_array + numpy_array)                    

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [12]:
print(bmi)
print(bmi[1])
print(bmi > 23)
print(bmi[bmi > 23])

[28.37370242 21.60493827 25.35154137 23.14049587 22.69401893]
21.604938271604937
[ True False  True  True False]
[28.37370242 25.35154137 23.14049587]
